# Generated by Django 5.2.1 on 2025-05-10 23:49

from decimal import Decimal

from django.db import migrations


def create_default_departments_positions(apps, schema_editor):
    Department = apps.get_model("employees", "Department")
    Position = apps.get_model("employees", "Position")

    # Create departments
    management = Department.objects.create(
        name="Management",
        description="Executive and management team overseeing all operations",
    )

    operations = Department.objects.create(
        name="Operations",
        description="Day-to-day operations of theaters and facilities",
    )

    marketing = Department.objects.create(
        name="Marketing", description="Marketing, promotions, and customer engagement"
    )

    sales = Department.objects.create(
        name="Sales", description="Sales, customer service, and ticket management"
    )

    technical = Department.objects.create(
        name="Technical", description="IT, software development, and technical support"
    )

    finance = Department.objects.create(
        name="Finance",
        description="Financial operations, accounting, and revenue management",
    )

    hr = Department.objects.create(
        name="Human Resources",
        description="Employee management, hiring, and HR operations",
    )

    # Create positions for Management department
    Position.objects.create(
        title="General Manager",
        department=management,
        description="Oversees all theater operations and department managers",
        min_salary=Decimal("80000.00"),
        max_salary=Decimal("120000.00"),
    )

    Position.objects.create(
        title="Assistant Manager",
        department=management,
        description="Assists the general manager with daily operations",
        min_salary=Decimal("60000.00"),
        max_salary=Decimal("85000.00"),
    )

    # Create positions for Operations department
    Position.objects.create(
        title="Operations Manager",
        department=operations,
        description="Oversees daily theater operations",
        min_salary=Decimal("55000.00"),
        max_salary=Decimal("80000.00"),
    )

    Position.objects.create(
        title="Theater Supervisor",
        department=operations,
        description="Supervises theater staff and ensures smooth operations during showtimes",
        min_salary=Decimal("45000.00"),
        max_salary=Decimal("60000.00"),
    )

    Position.objects.create(
        title="Facility Technician",
        department=operations,
        description="Maintains theater equipment and facilities",
        min_salary=Decimal("35000.00"),
        max_salary=Decimal("52000.00"),
    )

    # Create positions for Marketing department
    Position.objects.create(
        title="Marketing Director",
        department=marketing,
        description="Develops and implements marketing strategies",
        min_salary=Decimal("65000.00"),
        max_salary=Decimal("95000.00"),
    )

    Position.objects.create(
        title="Social Media Coordinator",
        department=marketing,
        description="Manages social media presence and online engagement",
        min_salary=Decimal("40000.00"),
        max_salary=Decimal("55000.00"),
    )

    Position.objects.create(
        title="Graphic Designer",
        department=marketing,
        description="Creates promotional materials and visual content",
        min_salary=Decimal("42000.00"),
        max_salary=Decimal("58000.00"),
    )

    # Create positions for Sales department
    Position.objects.create(
        title="Sales Manager",
        department=sales,
        description="Oversees ticket sales and customer service",
        min_salary=Decimal("55000.00"),
        max_salary=Decimal("75000.00"),
    )

    Position.objects.create(
        title="Ticket Sales Representative",
        department=sales,
        description="Processes ticket sales and assists customers",
        min_salary=Decimal("30000.00"),
        max_salary=Decimal("42000.00"),
    )

    Position.objects.create(
        title="Customer Service Specialist",
        department=sales,
        description="Handles customer inquiries and resolves issues",
        min_salary=Decimal("32000.00"),
        max_salary=Decimal("45000.00"),
    )

    # Create positions for Technical department
    Position.objects.create(
        title="IT Manager",
        department=technical,
        description="Oversees technology systems and infrastructure",
        min_salary=Decimal("70000.00"),
        max_salary=Decimal("100000.00"),
    )

    Position.objects.create(
        title="Software Developer",
        department=technical,
        description="Develops and maintains software applications",
        min_salary=Decimal("65000.00"),
        max_salary=Decimal("95000.00"),
    )

    Position.objects.create(
        title="Technical Support Specialist",
        department=technical,
        description="Provides technical support for systems and users",
        min_salary=Decimal("45000.00"),
        max_salary=Decimal("65000.00"),
    )

    # Create positions for Finance department
    Position.objects.create(
        title="Finance Manager",
        department=finance,
        description="Oversees financial operations and reporting",
        min_salary=Decimal("65000.00"),
        max_salary=Decimal("95000.00"),
    )

    Position.objects.create(
        title="Accountant",
        department=finance,
        description="Manages accounting and financial records",
        min_salary=Decimal("50000.00"),
        max_salary=Decimal("75000.00"),
    )

    Position.objects.create(
        title="Payroll Specialist",
        department=finance,
        description="Processes payroll and employee compensation",
        min_salary=Decimal("42000.00"),
        max_salary=Decimal("58000.00"),
    )

    # Create positions for HR department
    Position.objects.create(
        title="HR Manager",
        department=hr,
        description="Oversees human resources functions and policies",
        min_salary=Decimal("60000.00"),
        max_salary=Decimal("85000.00"),
    )

    Position.objects.create(
        title="Recruiter",
        department=hr,
        description="Sources and evaluates candidates for open positions",
        min_salary=Decimal("45000.00"),
        max_salary=Decimal("65000.00"),
    )

    Position.objects.create(
        title="Training Coordinator",
        department=hr,
        description="Develops and implements employee training programs",
        min_salary=Decimal("40000.00"),
        max_salary=Decimal("55000.00"),
    )


def delete_default_departments_positions(apps, schema_editor):
    Department = apps.get_model("employees", "Department")
    Department.objects.all().delete()
    # This will also delete all Positions due to the cascade delete


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_default_departments_positions, delete_default_departments_positions
        ),
    ]
