# Generated by Django 5.2.1 on 2025-05-11 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('PERFORMANCE', 'Performance'), ('CUSTOMER', 'Customer'), ('INVENTORY', 'Inventory'), ('EMPLOYEE', 'Employee'), ('SYSTEM', 'System')], max_length=20)),
                ('display_type', models.CharField(choices=[('NUMBER', 'Number'), ('CURRENCY', 'Currency'), ('PERCENTAGE', 'Percentage'), ('TEXT', 'Text'), ('CHART_LINE', 'Line Chart'), ('CHART_BAR', 'Bar Chart'), ('CHART_PIE', 'Pie Chart')], max_length=20)),
                ('calculation_method', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('refresh_frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('for_admins', models.BooleanField(default=True)),
                ('for_moderators', models.BooleanField(default=True)),
                ('for_salesmen', models.BooleanField(default=False)),
                ('for_customers', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField(default=dict)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dashboard.metric')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('EMPLOYEE', 'Employee Report'), ('MOVIES', 'Movies and Shows Report'), ('FINANCE', 'Financial Report'), ('PERFORMANCE', 'Performance Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('template_data', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('for_admins', models.BooleanField(default=True)),
                ('for_moderators', models.BooleanField(default=True)),
                ('for_salesmen', models.BooleanField(default=False)),
                ('for_customers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='dashboard.reporttemplate')),
            ],
        ),
    ]
