# Generated by Django 5.2.1 on 2025-05-11 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotificationpreference_message_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_CANCELLATION', 'Booking Cancellation'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('TICKET_READY', 'Ticket Ready'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('SHOW_REMINDER', 'Show Reminder'), ('MOVIE_PREMIERE', 'Movie Premiere'), ('USER_INACTIVITY', 'User Inactivity'), ('PROMOTION', 'Promotion'), ('REVIEW_RESPONSE', 'Review Response')], default='SYSTEM_ANNOUNCEMENT', max_length=50),
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_f2898f_idx',
            old_name='notificatio_notific_d6e074_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.CharField(blank=True, help_text='Optional ID of related object (e.g. booking ID)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='movie_premieres',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='show_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_id'], name='notificatio_related_e02d8a_idx'),
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
